### ISSUE TITLE
WingetUI doesn't switch to another theme style when Windows theme changes

### ISSUE THREAD

**Issue by maicol07** [marticliment/WingetUI#117]
When I switch the Windows theme from Dark to Light, WingetUI is unreadable:
![image](https://user-images.githubusercontent.com/9463142/188572493-8df455d1-d97d-4f59-af2a-5b6c2e9adc7f.png)

Can you fix it?
Thanks

You can use [darkdetect](https://pypi.org/project/darkdetect) to detect which theme is selected.

**Comment by maicol07** [comment]
New release fixes this (almost completely)!
@martinet101 Maybe icons can be changed to their colored variant?

**Comment by martinet101** [comment]
Yes, this will come soon, but i have to discover how to do that without iterating through the entire list of items.

It will come, i promise

**Comment by martinet101** [comment]
The issue has been fixed (with an asterisk)

The app will swap the theme when the window is hidden, because the icons can't be redrawn and then a full window reload is needed. However, while the window is shown there won't be any glitch.

**Comment by maicol07** [comment]
@martinet101 seems the issue is here again in 1.5.0:
![image](https://user-images.githubusercontent.com/9463142/199270619-0846b76b-49d4-45c0-aeb2-b8af9a4a79bd.png)

**Comment by martinet101** [comment]
This issue was fixed on version 1.5.1, but I forgot to post that here.

Could you please confirm that this got fixed?

**Comment by maicol07** [comment]
> This issue was fixed on version 1.5.1, but I forgot to post that here.
> 
> Could you please confirm that this got fixed?

Yes, it seems to work fine!

**Comment by maicol07** [comment]
Just retried better, it seems the issue hasn't been solved.
This is my test in detail:
1. Open WingetUI
2. Change theme to Dark/Light
3. Close WingetUI to tray
4. Reopen WingetUI
5. WingetUI is still Light/Dark and doesn't change theme

**Comment by martinet101** [comment]
Yes, this is an expected behaviour, and due to incompatiblities with icon engines, this won't change soon (at least for the moment).

**Comment by maicol07** [comment]
@marticliment actually there is a small issue with Scoop dialog which may be related to this:
![image](https://user-images.githubusercontent.com/9463142/209786096-b37086bc-948a-47ba-b648-da19608e075b.png)
The Scoop buckets window is black when the theme is light

**Comment by marticliment** [comment]
Did this happen before?

**Comment by maicol07** [comment]
Yes


------ Messaggio originale ------
Da "Martí Climent" ***@***.***>
A "marticliment/WingetUI" ***@***.***>
Cc "Maicol Battistini" ***@***.***>; "Author" 
***@***.***>
Data 28/12/2022 10:49:04
Oggetto Re: [marticliment/WingetUI] WingetUI doesn't switch to another 
theme style when Windows theme changes (Issue #117)

**Comment by marticliment** [comment]
This issue should be fixed on version 1.6. 

Could you please check it out?

**Comment by maicol07** [comment]
No, the issue persists:

![](https://user-images.githubusercontent.com/9463142/218544420-4c159b7f-28f3-4b76-abc9-eb1925b790ee.png)

Scoop buckets section:

![](https://user-images.githubusercontent.com/9463142/218544466-e9fa18e0-c4ea-4431-a95d-2f34b2d5386b.png)

**Comment by marticliment** [comment]
Chanign the UI to another theme won't be possible, but I will try my best to fix it so it stays consistently on one single theme.

**Comment by maicol07** [comment]
This unfortunately isn't fixed in 1.6.2

**Comment by marticliment** [comment]
Can you please share:
1. System details (theme, os version, etc.)
2. A video of the procedure required to do that
3. WingetUI's log

**Comment by maicol07** [comment]
1.  Windows 11 Pro 25309
2. https://user-images.githubusercontent.com/9463142/222697261-a697e6e1-b770-4c2d-a2a4-05a9803a386a.mp4
3. 
```
C:\Users\Maicol\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\Maicol\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0035037994384765625 to load all language files
🔵 Starting main application...
🔵 Language file up-to-date
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
b'v1.4.10173\r\n'
None
updating winget
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
b'1.2.1\r\n'
None
Reactivation signal ignored: RaiseWindow_[1677839007.6499174]
b"Current Scoop version:\nv0.3.1 - Released at 2022-11-15\n\n'extras' bucket:\n21ee528e2 todolist: Update to version 8.1.20\n\n'main' bucket:\n9b95bfc1f dolt: Update to version 0.54.2\n\n'nerd-fonts' bucket:\nc09d970 LXGWNeoXiHei: Add version 1.007 (#220)\n\n"
None
{'wingetFound': True, 'scoopFound': True, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'v0.3.1 - Released at 2022-11-15', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
Can't disconnect
🟢 Starting winget search, winget on C:\Users\Maicol\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🔵 Starting choco search
🟢 Discover tab loaded
🟢 Found valid cache for chocolatey!
Can't disconnect
🟢 Starting winget search, winget on C:\Users\Maicol\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\Maicol\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Users\Maicol\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\Maicol\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
{'System language': 'default', 'Arabic - عربي\u200e (95%)': 'ar', 'Bulgarian - български (88%)': 'bg', 'Bangla - বাংলা (25%)': 'bn', 'Catalan - Català': 'ca', 'Czech - Čeština (95%)': 'cs', 'Danish - Dansk (47%)': 'da', 'German - Deutsch (88%)': 'de', 'English - English': 'en', 'Spanish - Castellano': 'es', 'French - Français': 'fr', 'Hindi - हिंदी (76%)': 'hi', 'Hungarian - Magyar': 'hu', 'Italian - Italiano': 'it', 'Indonesian - Bahasa Indonesia (22%)': 'id', 'Japanese - 日本語 (82%)': 'ja', 'Korean - 한국어 (92%)': 'ko', 'Dutch - Nederlands (95%)': 'nl', 'Polish - Polski (95%)': 'pl', 'Portuguese (Brazil) (95%)': 'pt_BR', 'Portuguese (Portugal) (95%)': 'pt_PT', 'Russian - Русский (76%)': 'ru', 'Serbian - Srpski (20%)': 'sr', 'Turkish - Türkçe (79%)': 'tr', 'Ukranian - Yкраї́нська (79%)': 'ua', 'Simplified Chinese (China) (95%)': 'zh_CN', 'Traditional Chinese (Taiwan) (95%)': 'zh_TW'}
['System language', 'Arabic - عربي\u200e (95%)', 'Bulgarian - български (88%)', 'Bangla - বাংলা (25%)', 'Catalan - Català', 'Czech - Čeština (95%)', 'Danish - Dansk (47%)', 'German - Deutsch (88%)', 'English - English', 'Spanish - Castellano', 'French - Français', 'Hindi - हिंदी (76%)', 'Hungarian - Magyar', 'Italian - Italiano', 'Indonesian - Bahasa Indonesia (22%)', 'Japanese - 日本語 (82%)', 'Korean - 한국어 (92%)', 'Dutch - Nederlands (95%)', 'Polish - Polski (95%)', 'Portuguese (Brazil) (95%)', 'Portuguese (Portugal) (95%)', 'Russian - Русский (76%)', 'Serbian - Srpski (20%)', 'Turkish - Türkçe (79%)', 'Ukranian - Yкраї́нська (79%)', 'Simplified Chinese (China) (95%)', 'Traditional Chinese (Taiwan) (95%)']
it
{'default': 'System language', 'ar': 'Arabic - عربي\u200e (95%)', 'bg': 'Bulgarian - български (88%)', 'bn': 'Bangla - বাংলা (25%)', 'ca': 'Catalan - Català', 'cs': 'Czech - Čeština (95%)', 'da': 'Danish - Dansk (47%)', 'de': 'German - Deutsch (88%)', 'en': 'English - English', 'es': 'Spanish - Castellano', 'fr': 'French - Français', 'hi': 'Hindi - हिंदी (76%)', 'hu': 'Hungarian - Magyar', 'it': 'Italian - Italiano', 'id': 'Indonesian - Bahasa Indonesia (22%)', 'ja': 'Japanese - 日本語 (82%)', 'ko': 'Korean - 한국어 (92%)', 'nl': 'Dutch - Nederlands (95%)', 'pl': 'Polish - Polski (95%)', 'pt_BR': 'Portuguese (Brazil) (95%)', 'pt_PT': 'Portuguese (Portugal) (95%)', 'ru': 'Russian - Русский (76%)', 'sr': 'Serbian - Srpski (20%)', 'tr': 'Turkish - Türkçe (79%)', 'ua': 'Ukranian - Yкраї́нська (79%)', 'zh_CN': 'Simplified Chinese (China) (95%)', 'zh_TW': 'Traditional Chinese (Taiwan) (95%)'}
Can't disconnect
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Chocolatey uninstallable packages search finished
🟢 Searching for string ""
🟢 Chocolatey search finished
🟢 Searching for string ""
Name                                                        Id                                Version      Available
🟢 Winget search finished
Discord.Discord.PTB was blackisted
Ubisoft.Connect was blackisted
Microsoft.VCRedist.2013.x86 was blackisted
Microsoft.DotNet.DesktopRuntime.7 was blackisted
Microsoft.DotNet.DesktopRuntime.7 was blackisted
Microsoft.DotNet.DesktopRuntime.7 was blackisted
Microsoft.DotNet.DesktopRuntime.7 was blackisted
Microsoft.Teams was blackisted
Microsoft.VCRedist.2013.x86 was blackisted
🟢 Searching for string ""
pipeline.
list index out of range list index out of range
['pipeline.']
IndexError: list index out of range
In C:\Users\Maicol\scoop\apps\scoop\current\lib\buckets.ps1:103 car:70
['In', 'C:\\Users\\Maicol\\scoop\\apps\\scoop\\current\\lib\\buckets.ps1:103', 'car:70']
IndexError: list index out of range
+ ...     $bucket.Updated = git -C $path log --format='%aD' -n 1 | Get-Date
+                                                                  ~~~~~~~~
['+', '~~~~~~~~']
IndexError: list index out of range
+ CategoryInfo          : InvalidArgument: (Fri, 3 Mar 2023 08:28:01 +0000:PSObject) [Get-Date], ParameterBindingE
xception
list index out of range list index out of range
['xception']
IndexError: list index out of range
+ FullyQualifiedErrorId : InputObjectNotBound,Microsoft.PowerShell.Commands.GetDateCommand
['+', 'FullyQualifiedErrorId', ':', 'InputObjectNotBound,Microsoft.PowerShell.Commands.GetDateCommand']
IndexError: list index out of range
Get-Date : Impossibile associare l'oggetto di input a qualsiasi parametro del comando. Il comando non accetta l'input
da pipeline oppure l'input e le relative propriet non corrispondono ad alcun parametro che accetta l'input da
pipeline.
list index out of range list index out of range
['pipeline.']
IndexError: list index out of range
In C:\Users\Maicol\scoop\apps\scoop\current\lib\buckets.ps1:103 car:70
['In', 'C:\\Users\\Maicol\\scoop\\apps\\scoop\\current\\lib\\buckets.ps1:103', 'car:70']
IndexError: list index out of range
+ ...     $bucket.Updated = git -C $path log --format='%aD' -n 1 | Get-Date
+                                                                  ~~~~~~~~
['+', '~~~~~~~~']
IndexError: list index out of range
+ CategoryInfo          : InvalidArgument: (Fri, 3 Mar 2023 08:29:55 +0000:PSObject) [Get-Date], ParameterBindingE
xception
list index out of range list index out of range
['xception']
IndexError: list index out of range
+ FullyQualifiedErrorId : InputObjectNotBound,Microsoft.PowerShell.Commands.GetDateCommand
['+', 'FullyQualifiedErrorId', ':', 'InputObjectNotBound,Microsoft.PowerShell.Commands.GetDateCommand']
IndexError: list index out of range
Get-Date : Impossibile associare l'oggetto di input a qualsiasi parametro del comando. Il comando non accetta l'input
da pipeline oppure l'input e le relative propriet non corrispondono ad alcun parametro che accetta l'input da
pipeline.
list index out of range list index out of range
['pipeline.']
IndexError: list index out of range
In C:\Users\Maicol\scoop\apps\scoop\current\lib\buckets.ps1:103 car:70
['In', 'C:\\Users\\Maicol\\scoop\\apps\\scoop\\current\\lib\\buckets.ps1:103', 'car:70']
IndexError: list index out of range
+ ...     $bucket.Updated = git -C $path log --format='%aD' -n 1 | Get-Date
+                                                                  ~~~~~~~~
['+', '~~~~~~~~']
IndexError: list index out of range
+ CategoryInfo          : InvalidArgument: (Wed, 1 Mar 2023 17:15:22 +0800:PSObject) [Get-Date], ParameterBindingE
xception
list index out of range list index out of range
['xception']
IndexError: list index out of range
+ FullyQualifiedErrorId : InputObjectNotBound,Microsoft.PowerShell.Commands.GetDateCommand
['+', 'FullyQualifiedErrorId', ':', 'InputObjectNotBound,Microsoft.PowerShell.Commands.GetDateCommand']
IndexError: list index out of range
Name       Source                                             Updated Manifests
['Name', 'Source', 'Updated', 'Manifests']
IndexError: list index out of range
extras     https://github.com/ScoopInstaller/Extras                        1784
['extras', 'https://github.com/ScoopInstaller/Extras', '1784']
IndexError: list index out of range
main       https://github.com/ScoopInstaller/Main                          1170
['main', 'https://github.com/ScoopInstaller/Main', '1170']
IndexError: list index out of range
nerd-fonts https://github.com/matthewjberger/scoop-nerd-fonts               215
['nerd-fonts', 'https://github.com/matthewjberger/scoop-nerd-fonts', '215']
IndexError: list index out of range
🟢 Scoop bucket search finished
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 265
None
🟢 Winget search finished
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 3
🟢 Scoop search finished
🟢 Total packages: 10963
🔵 Copying log to the clipboard...
    ```

**Comment by marticliment** [comment]
Hello, 

I have tested WingetUI 1.7.1 with regular, beta and dev channel windows 11, and I am not able to recreate this issue.

Which version of Windows 11 are you running?
Also, how can I get it?

**Comment by maicol07** [comment]
Hi,
I'm currently using Windows 11 Canary 25352.1. Here's a video (zipped due to Github upload size restrictions) about the issue and how to reproduce it:
[wingetui_theme_issue.zip](https://github.com/marticliment/WingetUI/files/11365214/wingetui_theme_issue.zip)
> Note: The video was recorded on a plain Windows sandbox. Due to how Windows sandbox works, it isn't activated so I can't change theme via settings: to do it I've used [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) and forced the theme, but the same result can be achieved via Windows settings.

**Comment by marticliment** [comment]
Hello @maicol07,

I have been recreating this issue, and it only appears to happen on Canary builds. Dev and beta builds do not present this issue, and I am afraid that this is due to some kind of bug in the Windows API. Since the python script works fine, and it is the api who is not working as expected, this issue can't be really fixed.

I recommend you to install a non-canary version of Windows, because canary/dev builds tend to be really unstable.

**Comment by maicol07** [comment]
> Hello @maicol07,
> 
> I have been recreating this issue, and it only appears to happen on Canary builds. Dev and beta builds do not present this issue, and I am afraid that this is due to some kind of bug in the Windows API. Since the python script works fine, and it is the api who is not working as expected, this issue can't be really fixed.
> 
> I recommend you to install a non-canary version of Windows, because canary/dev builds tend to be really unstable.

Hi,  
I've currently switched to dev which shows this issue

**Comment by marticliment** [comment]
This issue was caused by the library used to paint the mica backdrop. 

The new version of the library will be present on the next version of WingetUI

**Comment by maicol07** [comment]
It seems that the latest rc fixes the issue only for dark mode. When switching from dark mode to light mode WingetUI keeps the dark mode

**Comment by marticliment** [comment]
Yes, WingetUI won't support hot theme changes, only supports theme change upon full app restart
