### ISSUE TITLE
[BUG] duplicate packages in discovery section

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1373]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

dummy packages appear when searching on the discovery section (moniker, tags, etc.) 
it increases according to the number of queries (see below)

### Steps to reproduce the issue

search winget pkgs on discovery section

### WingetUI Log

[log1.txt](https://github.com/marticliment/WingetUI/files/12657296/log1.txt)

### Package Managers Logs

[log2.txt](https://github.com/marticliment/WingetUI/files/12657297/log2.txt)

### Relevant information

maybe related to https://github.com/marticliment/WingetUI/issues/1334

### Screenshots and videos

first query

<img width="960" alt="Screenshot 2023-09-19 094311" src="https://github.com/marticliment/WingetUI/assets/73800734/b295acfb-bfd0-4d2f-bb92-1d11a0e76b57">

second query 

<img width="960" alt="Screenshot 2023-09-19 094603" src="https://github.com/marticliment/WingetUI/assets/73800734/2c086bc5-6801-46af-a27e-5b7984db48b0">

**Comment by ppvnf** [comment]
I think some time ago you fixed something similar, but I am not quite sure what it was

**Comment by ppvnf** [comment]
Also, I don't think this is limited to winget, I have tried disabling it and scoop packages appeared as duplicated instead

**Comment by ppvnf** [comment]
<img width="791" alt="Screenshot 2023-09-29 094234" src="https://github.com/marticliment/WingetUI/assets/73800734/28cd36bf-6cbc-4480-a19b-5308b5eef00c">
I encountered this again today

**Comment by ppvnf** [comment]
After restarting the system the bug disappeared. I have no idea what was the cause

**Comment by ppvnf** [comment]
I managed to reproduce it by unselecting/selecting sources/refreshing a few times, might be related to https://github.com/marticliment/WingetUI/issues/1397 since it also triggers infinite reloading

**Comment by marticliment** [comment]
I haven't managed to reproduce it again, please text the next version (coming today) and let me know

**Comment by ppvnf** [comment]
yes, it was fixed

**Comment by ppvnf** [comment]
it still happens
[1.txt](https://github.com/marticliment/WingetUI/files/12887621/1.txt)
[2.txt](https://github.com/marticliment/WingetUI/files/12887622/2.txt)
<img width="960" alt="Screenshot 2023-10-13 004733" src="https://github.com/marticliment/WingetUI/assets/73800734/e95b55ac-18f2-4fc7-b464-c9f8b1e09ec9">
possibly same as https://github.com/marticliment/WingetUI/discussions/1480

**Comment by Psycho-Fox** [comment]
This still happens 

<img width="298" height="532" alt="Image" src="https://github.com/user-attachments/assets/1547bdc4-1215-4c4f-911b-0e5f40915b8b" />

**Comment by marticliment** [comment]
update to 3.3.4

**Comment by Psycho-Fox** [comment]
> update to 3.3.4

I was on 3.3.4 when that screenshot was taken I'm on 3.3.5 now I hope it's fixed.
