### ISSUE TITLE
[BUG] wingetui shows wrong package update to different tool

### ISSUE THREAD

**Issue by phit42** [marticliment/WingetUI#2327]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

wingetui shows different (and less) updates than winget does. 
In particular, it shows an update that is none: package Synology.NoteStationClient 2.2.4-703 is offered as an update to the completely different tool "Synology Surveillance Station Client" version 2.2.0.2507, which is not a package as far as I can see, but has been installed manually.

### Steps to reproduce the issue

Install Surveillance Station Client. Let wingetui find updates.

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.2
               Version Code 3,02
C:\Users\Benutzer\AppData\Local\WingetUI\CachedLangFiles\lang_de.json
Loaded language locale: de
Api auth token: xxx
Starting update check
Api running on http://localhost:7058
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at ModernWindow.Core.Data.LanguageEngine.UpdateLanguageFile(String LangKey) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\Core\Data\LanguageData.cs:line 104
WingetUI is up to date
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Downloaded icons and screenshots successfully!
Winget source update timed out. Current output was
System.TimeoutException: The operation has timed out.
   at ModernWindow.MainApp.InitializeAllManagersAsync() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\App.xaml.cs:line 252
Timeout: Not all package managers have finished initializing.
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
   -    \    |    /    -    \    |    /    -    \    |    /    -    \    |    /    - 
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Chocolatey sources took too long to load, using known sources as default
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Program Files\WingetUI\choco-cli\bin\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Windows\system32'. Das System kann die angegebene Datei nicht finden.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
PowerShell sources took too long to load, using known sources as default
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.19041.4522                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.19041.4522                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Starting check for updates wait interval with waitTime=172800
Starting update check
WingetUI is up to date
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Windows\system32'. Das System kann die angegebene Datei nicht finden.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:02] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[19.06.2024 22:46:02] Exit Code: -2147450735
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:03] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\choco-cli\bin\choco.exe
█  Arguments:  list
xxx
4 packages installed.
[19.06.2024 22:46:03] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:06] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
WARNUNG: MSG:UnableToDownload �https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409� ��
WARNUNG: Unable to download the list of available providers. Check your internet connection.
Version    Name                                Repository           Description                                        
-------    ----                                ----------           -----------                                        
1.4.7      PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way t...
[19.06.2024 22:46:06] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:08] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  list  --accept-source-agreements
   \ 
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 5.75 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 5.75 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 5.75 MB
  ████████████████████▒▒▒▒▒▒▒▒▒▒  4.00 MB / 5.75 MB
  ██████████████████████████▒▒▒▒  5.00 MB / 5.75 MB
  ██████████████████████████████  5.75 MB / 5.75 MB
  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 11.1 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 11.1 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 11.1 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 11.1 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 11.1 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 11.1 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 11.1 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 11.1 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 11.1 MB
  ██████████████████████████▒▒▒▒  10.0 MB / 11.1 MB
  █████████████████████████████▒  11.0 MB / 11.1 MB
  ██████████████████████████████  11.1 MB / 11.1 MB
   - 
   | 
Name                                      Id                                        Version            Available Source
-----------------------------------------------------------------------------------------------------------------------
xxx
Synology Surveillance Station Client      Synology.NoteStationClient                2.2.0.2507         2.2.4-703 winget
xxx
[19.06.2024 22:46:08] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:24] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\choco-cli\bin\choco.exe
█  Arguments:  outdated
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?
Chocolatey has determined 0 package(s) are outdated. 
[19.06.2024 22:46:24] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:24] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: 
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
Lernen Sie das neue plattform�bergreifende PowerShell kennen - https://aka.ms/pscore6
Loading own PowerShell functions from:
C:\Users\Matthias\Documents\WindowsPowerShell\Functions
PS C:\Windows\system32> 
PS C:\Windows\system32>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{}
>>                         @(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                                 Write-Output($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
WARNUNG: MSG:UnableToDownload �https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409� ��
WARNUNG: Unable to download the list of available providers. Check your internet connection.
PS C:\Windows\system32>                 exit
Invoke-WebRequest : Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
In Zeile:11 Zeichen:33
+ ...     $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Split-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es sich um eine leere Zeichenfolge 
handelt.
In Zeile:12 Zeichen:61
+ ... -Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupk ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Spli 
   tPathCommand
[19.06.2024 22:46:24] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19.06.2024 22:46:26] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  update --include-unknown  --accept-source-agreements
   \ 
  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 11.1 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 11.1 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 11.1 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 11.1 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 11.1 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 11.1 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 11.1 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 11.1 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 11.1 MB
  ██████████████████████████▒▒▒▒  10.0 MB / 11.1 MB
  █████████████████████████████▒  11.0 MB / 11.1 MB
  ██████████████████████████████  11.1 MB / 11.1 MB
   - 
   | 
Name                                 Id                            Version        Available      Source
-------------------------------------------------------------------------------------------------------
Bitwarden                            Bitwarden.Bitwarden           2024.6.1       2024.6.2       winget
FreeCommander XE                     MarekJasinski.FreeCommanderXE Unknown        2024.0.0.900   winget
Google Play Spiele (Beta)            Google.PlayGames.Beta         24.5.760.6     128.0.6537.0   winget
Kodi                                 XBMCFoundation.Kodi           Unknown        21.0.0.0       winget
Stardock Fences 4                    Stardock.Fences               4.2.1.2        4.2.2.1        winget
Albion Online                        Albion.Online                 Unknown        20231106193145 winget
Synology Surveillance Station Client Synology.NoteStationClient    2.2.0.2507     2.2.4-703      winget
Zoom Workplace                       Zoom.Zoom                     6.0.11 (39959) 6.1.41135      winget
Teams Machine-Wide Installer         Microsoft.Teams.Classic       1.4.0.19572    1.7.00.15969   winget
Epic Games Launcher                  EpicGames.EpicGamesLauncher   1.3.82.0       1.3.93.0       winget
10 upgrades available.
[19.06.2024 22:46:26] Exit Code: 0
```

### Relevant information

Here in comparison the output of winget command line:
`C:\Users\Benutzer>winget update --include-unknown
Name                                             ID                                Version        Verfügbar            Quelle
-----------------------------------------------------------------------------------------------------------------------------
Bitwarden                                        Bitwarden.Bitwarden               2024.6.1       2024.6.2             winget
FreeCommander XE                                 MarekJasinski.FreeCommanderXE     Unknown        2024.0.0.900         winget
Google Play Spiele (Beta)                        Google.PlayGames.Beta             24.5.760.6     128.0.6537.0         winget
FFmpeg                                           Gyan.FFmpeg                       6.0            7.0.1                winget
Kodi                                             XBMCFoundation.Kodi               Unknown        21.0.0.0             winget
Stardock Fences 4                                Stardock.Fences                   4.2.1.2        4.2.2.1              winget
Albion Online                                    Albion.Online                     Unknown        20231106193145       winget
Zoom Workplace                                   Zoom.Zoom                         6.0.11 (39959) 6.1.41135            winget
Microsoft Windows Desktop Runtime - 6.0.31 (x64) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0        8.0.6                winget
Microsoft Windows Desktop Runtime - 7.0.20 (x64) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0        8.0.6                winget
Teams Machine-Wide Installer                     Microsoft.Teams                   1.4.0.19572    24137.2216.2931.2440 winget
Epic Games Launcher                              EpicGames.EpicGamesLauncher       1.3.82.0       1.3.93.0             winget
Microsoft Windows Desktop Runtime - 6.0.31 (x86) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0        8.0.6                winget
13 Aktualisierungen verfügbar.`

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/5514487/1daed1c6-d23c-420b-8798-9cfc099d5c6c)

**Comment by marticliment** [comment]
Please try using the latest UniGetUI beta release

**Comment by phit42** [comment]
Sorry, how do I do that?

**Comment by marticliment** [comment]
Download from here: https://github.com/marticliment/WingetUI/releases/tag/3.1.0-alpha1

**Comment by phit42** [comment]
UniGetUI doesn't show any installed packages beside PowerShell PackageManagement. Thus no updates either.

**Comment by phit42** [comment]
BTW reset of the winget sources, which should have resulted in showing packages, gets stuck forever on the circling stick:
![image](https://github.com/marticliment/WingetUI/assets/5514487/344a33bc-7bc5-4005-b504-4cf6d6817d6e)

**Comment by marticliment** [comment]
This issue has been fixed by [`UniGetUI 3.1.0 beta 0`](https://github.com/marticliment/WingetUI/releases/tag/3.1.0-beta0).

**Comment by phit42** [comment]
Thank you, I tried beta 0, but UniGetUI still doesn't show any installed packages beside PowerShell PackageManagement.

**Comment by marticliment** [comment]
please run on a powershell window
```
Install-Module Microsoft.WinGet.Client
```
and try to run UniGetUI again

**Comment by phit42** [comment]
This send me down a wild chase, as the install-module doesn't work. I now found out that any command in powershell cannot connect to any remote server - I don't know though why that is. I tried a lot of things, including tls12 setting etc, but nothing works. The gallery link (and others) can be accessed via browser though, so it doesn't seem to be a dns or firewall issue.
