### ISSUE TITLE
[BUG] UniGetUI does't list any Software Updates

### ISSUE THREAD

**Issue by darkred** [marticliment/WingetUI#2361]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 beta 0

### Windows version, edition and architecture

Windows 11 Pro 10.0.22631.3810 x64 23H2

### Describe your issue

UniGetUI does't list any packages for me.

I've tried `Reset Winget Sources` from the [pinned issue](https://github.com/marticliment/WingetUI/issues/1721#issue-2091348798) as well as deleting the folders from its [latest comment](https://github.com/marticliment/WingetUI/issues/1721#issuecomment-2138879620), but didn't help. I also tried uninstalling UnigetUI and manually deleting `%LocalAppData%\UniGetUI` but no change.

Using UniGetUI 3.1.0 beta 0 and Winget CLI 1.8.1791 stable on win 11.

### Steps to reproduce the issue

Switch to 'Software Updates' tab (no updates are listed).
Click the circle arrow to search for updates, no updates are found.

### UniGetUI Log

```text
[29/6/2024 20:25:02] 
                        __  __      _ ______     __  __  ______
                       / / / /___  (_) ____/__  / /_/ / / /  _/
                      / / / / __ \/ / / __/ _ \/ __/ / / // /  
                     / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                     \____/_/ /_/_/\____/\___/\__/\____/___/   
                         Welcome to UniGetUI Version 3.1.0-beta0
[29/6/2024 20:25:02]
[29/6/2024 20:25:02] Version Code:  3.0992
[29/6/2024 20:25:02] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[29/6/2024 20:25:02] LoadLanguageFile Failed for LangKey=en_US, ForceBundled=True
[29/6/2024 20:25:02] System.IO.FileNotFoundException: Could not find file 'C:\Program Files\UniGetUI\Assets\Languages\lang_en_US.json'.
                     File name: 'C:\Program Files\UniGetUI\Assets\Languages\lang_en_US.json'
                        at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                        at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                        at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                        at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                        at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
                        at System.IO.File.ReadAllText(String path, Encoding encoding)
                        at UniGetUI.Core.Language.LanguageEngine.LoadLanguageFile(String LangKey, Boolean ForceBundled) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 66
[29/6/2024 20:25:02] Loaded language locale: en
[29/6/2024 20:25:03] Api auth token: mw9dexnmaamk8fpf6cwzl9179f21kwzzqjwoge50i61f5gb6wy9oxiq2umg0h3q6
[29/6/2024 20:25:03] Api running on http://localhost:7058
[29/6/2024 20:25:03] Downloaded new icons and screenshots successfully!
[29/6/2024 20:25:03] UniGetUI is up to date
[29/6/2024 20:25:03] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: .NET Tool
                     █ Enabled: True
                     █ Found: True
                     █ Fancye exe name: dotnet tool
                     █ Executable path: C:\Program Files\dotnet\dotnet.exe
                     █ Call arguments: tool
                     █ Version: 
                     █   
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:03] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Pip
                     █ Enabled: True
                     █ Found: True
                     █ Fancye exe name: pip
                     █ Executable path: C:\Users\Kostas\AppData\Local\Microsoft\WindowsApps\python.exe
                     █ Call arguments:  -m pip
                     █ Version: 
                     █   
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:04] Command scoop was not found on the system
[29/6/2024 20:25:04] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Scoop
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:04] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Npm
                     █ Enabled: True
                     █ Found: True
                     █ Fancye exe name: npm
                     █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                     █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                     █ Version: 
                     █   10.8.1
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:05] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Chocolatey
                     █ Enabled: True
                     █ Found: True
                     █ Fancye exe name: choco.exe
                     █ Executable path: C:\Users\Kostas\AppData\Local\UniGetUI\Chocolatey\choco.exe
                     █ Call arguments: 
                     █ Version: 
                     █   2.2.2
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:05] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: PowerShell
                     █ Enabled: True
                     █ Found: True
                     █ Fancye exe name: powershell.exe
                     █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                     █ Call arguments:  -NoProfile -Command
                     █ Version: 
                     █   Name                           Value                                                                                   
                     █   ----                           -----                                                                                   
                     █   PSVersion                      5.1.22621.3810                                                                          
                     █   PSEdition                      Desktop                                                                                 
                     █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                     █   BuildVersion                   10.0.22621.3810                                                                         
                     █   CLRVersion                     4.0.30319.42000                                                                         
                     █   WSManStackVersion              3.0                                                                                     
                     █   PSRemotingProtocolVersion      2.3                                                                                     
                     █   SerializationVersion           1.1.0.1
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:06] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Winget
                     █ Enabled: True
                     █ Found: True
                     █ Fancye exe name: winget.exe
                     █ Executable path: C:\Users\Kostas\AppData\Local\Microsoft\WindowsApps\winget.exe
                     █ Call arguments: 
                     █ Version: 
                     █   Naive WinGet CLI Version: v1.8.1791
                     █   Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
                     █   -----  -----  -----  --------
                     █   1      8      1791   -1
                     █   Using Native WinGet helper (COM Api)
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[29/6/2024 20:25:06] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[29/6/2024 20:25:06] Command dotnet-tools-outdated.exe was not found on the system
[29/6/2024 20:25:07] Found 0 available updates from Pip
[29/6/2024 20:25:07] Found 0 installed packages from Pip
[29/6/2024 20:25:07] Error finding updates on manager .NET Tool
[29/6/2024 20:25:07] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'C:\Program Files\UniGetUI'. The system cannot find the file specified.
                        at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                        at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 90
                        at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[29/6/2024 20:25:07] Found 0 installed packages from Winget
[29/6/2024 20:25:07] Found 0 installed packages from .NET Tool
[29/6/2024 20:25:07] Found 0 installed packages from Chocolatey
[29/6/2024 20:25:07] Found 0 available updates from Chocolatey
[29/6/2024 20:25:08] Found 0 available updates from Winget
[29/6/2024 20:25:09] Found 1 installed packages from PowerShell
[29/6/2024 20:25:10] Found 11 installed packages from Npm
[29/6/2024 20:25:11] Found 0 available updates from PowerShell
[29/6/2024 20:25:11] Found 0 available updates from Npm
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1791   -1
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 29/6/2024 20:25:06
Process end time:   29/6/2024 20:25:06

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Kostas\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 29/6/2024 20:25:06
Process end time:   29/6/2024 20:25:07

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 29/6/2024 20:25:06
Process end time:   29/6/2024 20:25:07

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The 'Get-WinGetPackage' command was found in the module 'Microsoft.WinGet.Client', but the module 
  could not be loaded. For more information, run 'Import-Module Microsoft.WinGet.Client'.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 29/6/2024 20:25:06
Process end time:   29/6/2024 20:25:06

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 29/6/2024 20:25:07
Process end time:   29/6/2024 20:25:08

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The 'Get-WinGetPackage' command was found in the module 'Microsoft.WinGet.Client', but the module 
  could not be loaded. For more information, run 'Import-Module Microsoft.WinGet.Client'.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Relevant information

Also Installed packages lists only packages installed via npm and PSGallery:
(although all package managers are enabled in UnigetUI)
![2024-06-29_211840](https://github.com/marticliment/WingetUI/assets/723651/18c71e45-8649-458a-8fb4-e01e62e8a977)

### Screenshots and videos

As per FAQ `winget upgrade` works fine for me:
![2024-06-29_211028](https://github.com/marticliment/WingetUI/assets/723651/98c1d8ff-4cf1-4dea-95b1-c167918627f3)

Screenshot of UniGetUI's Software Updates empty tab:
![2024-06-29_211400](https://github.com/marticliment/WingetUI/assets/723651/74bda1b5-a55b-4cc9-af42-d3af29cbee50)

**Comment by marticliment** [comment]
please run on a powershell window

```
Uninstall-Module Microsoft.WinGet.Client
Install-Module Microsoft.WinGet.Client
```

**Comment by BNX070** [comment]
> please run on a powershell window
> 
> ```
> Uninstall-Module Microsoft.WinGet.Client
> Install-Module Microsoft.WinGet.Client
> ```

I'm also having the same issue, tried your solution but didn't work.

**Comment by darkred** [comment]
I ran `Uninstall-Module Microsoft.WinGet.Client` ok. Then tried `Install-Module Microsoft.WinGet.Client` resulted to:

> WARNING: Version '1.8.1133' of module 'Microsoft.WinGet.Client' is already installed at 'C:\Users\Kostas\Documents\PowerShell\Modules\Microsoft.WinGet.Client\1.8.1133'. To install version '1.8.1791', run Install-Module and add the -Force parameter, this command will install version '1.8.1791' side-by-side with version '1.8.1133'.

so I ran to `Install-Module Microsoft.WinGet.Client -Force` which completed with no errors, but unfortunately UniGetUI still doesn't list any Software Updates.

For reference here is list of all installed modules (`Get-InstalledModule` output):
![2024-06-29_223651](https://github.com/marticliment/WingetUI/assets/723651/c7416067-b065-4386-b476-3d903fafcfba)

**Comment by BNX070** [comment]
A total uninstall makes it work once launching after reinstall but doesn't the second time around.

**Comment by io43** [comment]
i just updated winget and i have same issue on wingetui

**Comment by fernandog** [comment]
have this issue. no installed apps. some errors on my logs:

[30/06/2024 00:30:46] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-beta0
[30/06/2024 00:30:46]
[30/06/2024 00:30:46] Version Code:  3,0992
[30/06/2024 00:30:47] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[30/06/2024 00:30:47] Loaded language locale: pt_BR
[30/06/2024 00:30:48] Api auth token: xwpeimaeq6yarr1xhqv7fbv9tm7pafn3jl8ard40zwi9nghwz9ixd061d3jdhf45
[30/06/2024 00:30:50] Api running on http://localhost:7058
[30/06/2024 00:30:50] Lang files were updated successfully from GitHub
[30/06/2024 00:30:50] UniGetUI is up to date
[30/06/2024 00:30:54] Command npm was not found on the system
[30/06/2024 00:30:54] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Program Files\UniGetUI\choco-cli\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:01] Downloaded new icons and screenshots successfully!
**[30/06/2024 00:31:01] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.PEInterface.Initialize() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageEngine\PEInterface.cs:line 44**
[30/06/2024 00:31:01] Timeout: Not all package managers have finished initializing.
[30/06/2024 00:31:01] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[30/06/2024 00:31:07] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: C:\Users\Fernando\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:08] Command dotnet-tools-outdated.exe was not found on the system
[30/06/2024 00:31:08] Found 0 available updates from Chocolatey
[30/06/2024 00:31:09] Found 0 installed packages from Chocolatey
[30/06/2024 00:31:09] Error finding updates on manager .NET Tool
**[30/06/2024 00:31:09] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'C:\Program Files\UniGetUI'. O sistema não pode encontrar o arquivo especificado.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 90
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180**
[30/06/2024 00:31:10] Found 0 installed packages from .NET Tool
[30/06/2024 00:31:13] Command scoop was not found on the system
[30/06/2024 00:31:13] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:30] PowerShell sources took too long to load, using known sources as default
[30/06/2024 00:31:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.19041.4597                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.19041.4597                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:30] Found 0 installed packages from Chocolatey
[30/06/2024 00:31:30] Found 0 installed packages from Pip
[30/06/2024 00:31:31] Found 0 installed packages from .NET Tool
[30/06/2024 00:31:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\Fernando\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.8.1791
                      █   Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
                      █   -----  -----  -----  --------
                      █   1      8      1791   -1
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30/06/2024 00:31:57] Found 1 installed packages from PowerShell

**Comment by fernandog** [comment]
Package manager logs:

Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1791   -1
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 30/06/2024 00:31:47
Process end time:   30/06/2024 00:31:47

-- Task information
 ...

The task reported success

——————————————————————————————————————————

**Comment by marticliment** [comment]
This issue was fixed here: https://github.com/marticliment/WingetUI/commit/7de960b986bea52540c0201b01773c2668f88c28#diff-c5edf1f9e67afdabfdd3506a6233f12e5e8cfd0a078623908926a0c95e94644e

**Comment by BNX070** [comment]
> This issue was fixed here: [7de960b#diff-c5edf1f9e67afdabfdd3506a6233f12e5e8cfd0a078623908926a0c95e94644e](https://github.com/marticliment/WingetUI/commit/7de960b986bea52540c0201b01773c2668f88c28#diff-c5edf1f9e67afdabfdd3506a6233f12e5e8cfd0a078623908926a0c95e94644e)

I'm still not getting any software updates.

Log1:
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1791   -1
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 6/30/2024 4:32:59 PM
Process end time:   6/30/2024 4:32:59 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\11111\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 6/30/2024 4:32:59 PM
Process end time:   6/30/2024 4:33:03 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 6/30/2024 4:33:00 PM
Process end time:   6/30/2024 4:33:08 PM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The 'Get-WinGetPackage' command was found in the module 'Microsoft.WinGet.Client', but the module 
  could not be loaded. For more information, run 'Import-Module Microsoft.WinGet.Client'.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 6/30/2024 4:33:02 PM
Process end time:   6/30/2024 4:33:03 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "powershell.exe"
Command-line arguments: ""
Process start time: 6/30/2024 4:33:03 PM
Process end time:   6/30/2024 4:33:11 PM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Set-ExecutionPolicy : The term '﻿Set-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script 
  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
  and try again.
  At line:1 char:1
  + ﻿Set-ExecutionPolicy Bypass -Scope Process -Force
  + ~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Set-ExecutionPolicy:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   
  Get-WinGetPackage : The 'Get-WinGetPackage' command was found in the module 'Microsoft.WinGet.Client', but the module 
  could not be loaded. For more information, run 'Import-Module Microsoft.WinGet.Client'.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
   

Return code: SUCCESS (0)

——————————————————————————————————————————
Log2:

[6/30/2024 4:32:49 PM] 
                          __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /  
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                       \____/_/ /_/_/\____/\___/\__/\____/___/   
                           Welcome to UniGetUI Version 3.1.0-beta0
[6/30/2024 4:32:49 PM]
[6/30/2024 4:32:49 PM] Version Code:  3.0992
[6/30/2024 4:32:49 PM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[6/30/2024 4:32:50 PM] Loaded language locale: en
[6/30/2024 4:32:50 PM] Api auth token: q2ainn3aqmai8k407wmhl50ir8jjm0jq7pxu64py9xj0mzulb7dpon5lf46dj848
[6/30/2024 4:32:51 PM] Api running on http://localhost:7058
[6/30/2024 4:32:52 PM] Could not download updated translations from GitHub
[6/30/2024 4:32:52 PM] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                          at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                          at UniGetUI.Core.Language.LanguageEngine.DownloadUpdatedLanguageFile(String LangKey) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 100
[6/30/2024 4:32:52 PM] UniGetUI is up to date
[6/30/2024 4:32:52 PM] Downloaded new icons and screenshots successfully!
[6/30/2024 4:32:53 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: True
                       █ Found: True
                       █ Fancye exe name: dotnet tool
                       █ Executable path: C:\Program Files\dotnet\dotnet.exe
                       █ Call arguments: tool
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:32:55 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: True
                       █ Found: True
                       █ Fancye exe name: npm
                       █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                       █ Version: 
                       █   10.8.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:32:55 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: True
                       █ Found: True
                       █ Fancye exe name: pip
                       █ Executable path: C:\Program Files\Python311\python.exe
                       █ Call arguments:  -m pip
                       █ Version: 
                       █   pip 24.1.1 from C:\Users\11111\AppData\Roaming\Python\Python311\site-packages\pip (python 3.11)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:32:57 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: True
                       █ Found: True
                       █ Fancye exe name: choco.exe
                       █ Executable path: C:\Users\11111\AppData\Local\UniGetUI\Chocolatey\choco.exe
                       █ Call arguments: 
                       █ Version: 
                       █   2.2.2
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:32:58 PM] Command scoop was not found on the system
[6/30/2024 4:32:58 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:32:58 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancye exe name: powershell.exe
                       █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.22621.3672                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.22621.3672                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:32:59 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancye exe name: winget.exe
                       █ Executable path: C:\Users\11111\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   Naive WinGet CLI Version: v1.8.1791
                       █   Microsoft.WinGet.Client PSModule version: Major  Minor  Build  Revision
                       █   -----  -----  -----  --------
                       █   1      8      1791   -1
                       █   Using Native WinGet helper (COM Api)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[6/30/2024 4:33:01 PM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[6/30/2024 4:33:03 PM] Command dotnet-tools-outdated.exe was not found on the system
[6/30/2024 4:33:04 PM] Error finding updates on manager .NET Tool
[6/30/2024 4:33:04 PM] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'C:\Program Files\UniGetUI'. The system cannot find the file specified.
                          at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                          at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 90
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 180
[6/30/2024 4:33:04 PM] Found 0 installed packages from .NET Tool
[6/30/2024 4:33:04 PM] Found 6 installed packages from Pip
[6/30/2024 4:33:04 PM] Found 0 available updates from Chocolatey
[6/30/2024 4:33:05 PM] Found 0 installed packages from Chocolatey
[6/30/2024 4:33:08 PM] Found 0 installed packages from Winget
[6/30/2024 4:33:09 PM] Found 0 available updates from Pip
[6/30/2024 4:33:09 PM] Found 1 installed packages from PowerShell
[6/30/2024 4:33:11 PM] Found 0 available updates from Winget
[6/30/2024 4:33:12 PM] Found 0 available updates from PowerShell
[6/30/2024 4:33:13 PM] Found 1 installed packages from Npm
[6/30/2024 4:33:13 PM] Found 0 available updates from Npm

**Comment by TechnoSparks** [comment]
I am having the same problem, UniGetUI says I have no packages found. In the installed section, in the left sidebar, sources is Empty
![image](https://github.com/marticliment/WingetUI/assets/6072210/3175de1a-77d8-4315-bc9b-6c65606bfcdd)
[UniGetUI Log.txt](https://github.com/user-attachments/files/16046863/UniGetUI.Log.txt)

**Comment by TechnoSparks** [comment]
I have downgraded to the Stable 3.0.2 and my installed packages populated correctly 
[WingetUI Log.txt](https://github.com/user-attachments/files/16046886/WingetUI.Log.txt)
![image](https://github.com/marticliment/WingetUI/assets/6072210/9b880bd4-2058-4c37-a059-8e7c112f3bbd)

**Comment by BNX070** [comment]
> I have downgraded to the Stable 3.0.2 and my installed packages populated correctly [WingetUI Log.txt](https://github.com/user-attachments/files/16046886/WingetUI.Log.txt) ![image](https://private-user-images.githubusercontent.com/6072210/344506153-9b880bd4-2058-4c37-a059-8e7c112f3bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTgyMjgsIm5iZiI6MTcxOTc5NzkyOCwicGF0aCI6Ii82MDcyMjEwLzM0NDUwNjE1My05Yjg4MGJkNC0yMDU4LTRjMzctYTA1OS04ZTdjMTEyZjNiYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDEzODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ4NGIzMDYxZjk4NzFiMjgyNTY3Y2RmYTc4OGRmNjlkNTIwOGU2NDQwMDZkMTU4MjVkNGQ3ZGY5OWRmYTljNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NHjaL4JtQMWgZInowJ65g4hb18edAkhNKyQoGTWG0UM)

Agreed! the stable does work for me too

**Comment by darkred** [comment]
The issue is fixed in the new beta, now UnigetUI detects Software Updates ok, thank you!

---

But I'm now having a different (unrelated) issue: I'm getting this "Missing dependency" prompt:
![2024-07-01_160131](https://github.com/marticliment/WingetUI/assets/723651/2a8e42ac-610a-4c3a-b9e9-a0cfa2a6919a)
I then press click "Install.NET Tools Outdated", a (probably Powershell window is displayed momentarily)_ and then click "Restart UniGetUI", but when UnigetUI restarts, I'm constantly getting the "Missing dependency" prompt.
