### ISSUE TITLE
[BUG/ISSUE] untranslatable texts

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#893]
<img width="395" alt="Screenshot 2023-04-10 101338" src="https://user-images.githubusercontent.com/73800734/230858518-5cca71e5-423e-42df-beab-01d3a75c7cfd.png">

**Comment by marticliment** [comment]
Done!

**Comment by ppvnf** [comment]
this phrase still appears untranslated:

_We could not load detailed information about this package, because it was not installed from an available package manager._

I think the two entries on Tolgee regarding it are outdated and should be removed:
<img width="861" alt="Screenshot 2023-04-10 120915" src="https://user-images.githubusercontent.com/73800734/230881696-db5ab1ee-776b-4a8f-abce-69e2ae3216c8.png">

**Comment by marticliment** [comment]
Done!

**Comment by ppvnf** [comment]
thanks, it seems fixed. But I don't understand why there is this line of code in uisections.py lines 409-425: `We could not load detailed information about this package, because it was found in any of your package sources`

Is it ever used?

**Comment by marticliment** [comment]
This is an open issue. a _not_ is missing here

**Comment by ppvnf** [comment]
Just a question, the following line will be deleted when the next update is released since it is no longer used, right?

<img width="566" alt="Screenshot 2023-04-10 142847" src="https://user-images.githubusercontent.com/73800734/230901719-b85db9ff-e669-412a-94e8-8c863c8796a2.png">

**Comment by marticliment** [comment]
Yes.

However, if it gets deleted now, it will be deleted for all users running WingetUI
